### ISSUE TITLE
java.lang.nosuchmethoderror While using in Apache NiFi

### ISSUE THREAD

**Issue by faisal-ksolves** [soulwing/tnm4j#27]
I am using this library in my Apache NiFi project, to perform a walk operation but it shows the following error 
`
java.lang.NoSuchMethodError: 'void net.percederberg.mibble.asn1.Asn1Parser.reset(java.io.Reader, net.percederberg.grammatica.parser.Analyzer)'
	at net.percederberg.mibble.MibLoader$MibSource.parseMib(MibLoader.java:970)
	at net.percederberg.mibble.MibLoader.loadQueue(MibLoader.java:724)
	at net.percederberg.mibble.MibLoader.load(MibLoader.java:550)
	at net.percederberg.mibble.MibLoader.load(MibLoader.java:451)
	at org.soulwing.snmp.provider.mibble.CachingMibRepository.load(CachingMibRepository.java:79)
	at org.soulwing.snmp.provider.mibble.MibbleMib.load(MibbleMib.java:226)
`
can you help me to resolves it.
Thanks in Advance.

**Comment by ceharris** [comment]
Are you using the same versions of the Mibble dependencies as those listed in the top level `pom.xml`?

**Comment by faisal-ksolves** [comment]
here is my complete pom.xml which is using tnm4j 1.2.0 in Apache NiFi
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<parent>
    <groupId>com.pnm</groupId>
    <artifactId>pnm</artifactId>
    <version>1.0</version>
</parent>

<artifactId>nifi-PNMtest-processors</artifactId>
<packaging>jar</packaging>

<dependencies>

    <dependency>
        <groupId>org.soulwing.snmp</groupId>
        <artifactId>tnm4j</artifactId>
        <version>1.2.0</version>
    </dependency>
    <dependency>
        <groupId>org.apache.nifi</groupId>
        <artifactId>nifi-api</artifactId>
    </dependency>
    <dependency>
        <groupId>org.apache.nifi</groupId>
        <artifactId>nifi-utils</artifactId>
        <version>1.20.0</version>
    </dependency>
    <dependency>
        <groupId>org.apache.nifi</groupId>
        <artifactId>nifi-mock</artifactId>
        <version>1.20.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <scope>test</scope>
    </dependency>
</dependencies>
`

**Comment by ceharris** [comment]
What version of Java are you using at runtime?

**Comment by faisal-ksolves** [comment]
Java version 1.8

**Comment by ceharris** [comment]
Are you able to run the examples, particularly `Example05_TableRetrievalUsingWalk`, as described in the README?

**Comment by faisal-ksolves** [comment]
It is working fine in normal Java project, but when Im using it with Apache
NIFi it shows the above error. You can create a sample NIFi project to test
it. It will explain you the best.

**Comment by ceharris** [comment]
I think that if you run `mvn dependency:tree` in your project, you'll find that one of Apache NiFi dependencies is pulling in a different version of the Mibble dependencies than what is listed in the `pom.xml` for Tnm4j. You can probably configure an exclusion in your project's `pom.xml` to keep that from happening.

 If you don't know how to interpret the output from `mvn dependency:tree`, I may be able to help with that.

**Comment by faisal-ksolves** [comment]
i try the mvn dependency:tree command and it shows the following data
[INFO] com.pnm:nifi-PNMtest-nar:nar:1.0
[INFO] +- com.pnm:nifi-PNMtest-processors:jar:1.0:compile
[INFO] |  +- org.soulwing.snmp:tnm4j:jar:1.2.0:compile
[INFO] |  |  +- org.snmp4j:snmp4j:jar:2.8.12:compile
[INFO] |  |  +- net.percederberg.mibble:mibble:jar:2.9.3:compile
[INFO] |  |  |  \- net.percederberg.grammatica:grammatica:jar:1.5:compile
[INFO] |  |  +- net.percederberg.mibble:mibble-mibs:jar:2.9.3:runtime
[INFO] |  |  \- org.slf4j:log4j-over-slf4j:jar:2.0.6:provided
[INFO] |  \- org.apache.nifi:nifi-utils:jar:1.20.0:compile
[INFO] |     \- org.apache.nifi:nifi-api:jar:1.20.0:provided
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.9.1:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.9.1:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.9.1:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.9.1:test
[INFO] +- org.junit.vintage:junit-vintage-engine:jar:5.9.1:test
[INFO] |  \- junit:junit:jar:4.13.2:test
[INFO] |     \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.junit.jupiter:junit-jupiter-params:jar:5.9.1:test
[INFO] +- org.mockito:mockito-core:jar:3.12.4:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.11.13:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.11.13:test
[INFO] |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] +- org.mockito:mockito-junit-jupiter:jar:3.12.4:test
[INFO] +- org.slf4j:slf4j-simple:jar:2.0.6:test
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.6:provided
[INFO] \- org.codehaus.groovy:groovy-test:jar:3.0.14:test
[INFO]    \- org.codehaus.groovy:groovy:jar:3.0.14:test

but surely there is no conflict.
can you help me.

Thanks

**Comment by ceharris** [comment]
No conflict with the dependencies such as you've configured them, so I suggest you take a very close look at the runtime environment in which you're using Apache NiFi. That `NoSuchMethodError` indicates that there's an incompatible version of the net.percederberg.mibble.asn1.Asn1Parser class on the runtime class path. 

I've offered as much help as I can offer at this point.
